development: &default
  adapter: postgresql
  database: mostacho-app-development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  host: localhost
  port: 5434

test:
  <<: *default
  database: mostacho-app-test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>